apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-sentry"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"  
spec:
  tls:
  - hosts:  
    - sentry.mywebsite.dev  
    secretName: "sentry.mywebsite.dev-tls"
  rules:
  - host: sentry.mywebsite.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-sentry-web"
            port: 
              number: 9000