user:
  create: true
  email: youremail@example.com
  password: admin
ingress:
  enabled: true
  # If you are using traefik ingress controller, switch this to 'traefik'
  regexPathStyle: nginx
  annotations:
  # If you are using nginx ingress controller, please use at least those 2 annotations
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
  hostname: sentry.example.com
sentry:
  singleOrganization: false
  worker:
    replicas: 2
service:
  name: sentry
  type: ClusterIP
  externalPort: 9000
  annotations: {}
hooks:
  activeDeadlineSeconds: 6500
clickhouse:
  enabled: true
  replicas: "1"
kafka:
    enabled: true
postgresql:
  enabled: false
## This value is only used when postgresql.enabled is set to false
externalPostgresql:
  host: database-host
  port: 5432
  username: postgres
  password: ""
  database: sentry